/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	"/apps/{appId}/sessions/new": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Create a new PeerConnection */
		post: {
			parameters: {
				query?: {
					/** @description Session is intended to connect to an ICE-lite peer like a third party SFU/server */
					thirdparty?: boolean;
					/** @description Associate session to an user-provided correlation id */
					correlationId?: string;
				};
				header?: never;
				path: {
					/** @description WebRTC application ID */
					appId: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description Created */
				201: {
					headers: {
						vary?: string;
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["NewSessionResponse"] &
							unknown;
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/apps/{appId}/adapters/websocket/new": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Create WebSocket adapter(s) for ingest or stream */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description WebRTC application ID */
					appId: string;
				};
				cookie?: never;
			};
			requestBody?: {
				content: {
					"application/json": components["schemas"]["NewAdapterRequest"];
				};
			};
			responses: {
				/** @description OK */
				200: {
					headers: {
						vary?: string;
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["NewAdapterResponse"];
					};
				};
				/** @description Service unavailable. No adapter could be created. */
				503: {
					headers: {
						vary?: string;
						[name: string]: unknown;
					};
					content: {
						/**
						 * @example {
						 *       "tracks": [
						 *         {
						 *           "trackName": "mic-track",
						 *           "errorCode": "adapter_unavailable",
						 *           "errorDescription": "Failed to create adapter"
						 *         }
						 *       ]
						 *     }
						 */
						"application/json": components["schemas"]["NewAdapterResponse"];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/apps/{appId}/adapters/websocket/close": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Close WebSocket adapter(s) */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description WebRTC application ID */
					appId: string;
				};
				cookie?: never;
			};
			requestBody?: {
				content: {
					/**
					 * @example {
					 *       "tracks": [
					 *         {
					 *           "adapterId": "4e66a9d5a35e4a0899f6f8d0b63a35c1"
					 *         }
					 *       ]
					 *     }
					 */
					"application/json": components["schemas"]["CloseAdapterRequest"];
				};
			};
			responses: {
				/** @description OK */
				200: {
					headers: {
						vary?: string;
						[name: string]: unknown;
					};
					content: {
						/**
						 * @example {
						 *       "tracks": [
						 *         {
						 *           "adapterId": "4e66a9d5a35e4a0899f6f8d0b63a35c1",
						 *           "bytesProcessed": 83492
						 *         }
						 *       ]
						 *     }
						 */
						"application/json": components["schemas"]["CloseAdapterResponse"];
					};
				};
				/** @description Service unavailable. No adapter could be closed. */
				503: {
					headers: {
						vary?: string;
						[name: string]: unknown;
					};
					content: {
						/**
						 * @example {
						 *       "tracks": [
						 *         {
						 *           "adapterId": "4e66a9d5a35e4a0899f6f8d0b63a35c1",
						 *           "errorCode": "adapter_not_found",
						 *           "errorDescription": "Adapter not found"
						 *         }
						 *       ]
						 *     }
						 */
						"application/json": components["schemas"]["CloseAdapterResponse"];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/apps/{appId}/sessions/{sessionId}/tracks/new": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Solve the given track object(s) and add the track(s) to the WebRTC session */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description WebRTC application ID */
					appId: string;
					/** @description Current PeerConnection session ID */
					sessionId: string;
				};
				cookie?: never;
			};
			requestBody?: {
				content: {
					"application/json": components["schemas"]["TracksRequest"];
				};
			};
			responses: {
				/** @description OK */
				200: {
					headers: {
						vary?: string;
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["TracksResponse"];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/apps/{appId}/sessions/{sessionId}/renegotiate": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		/** When a previous response has requiresImmediateRenegotiation, you must renegotiate */
		put: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description WebRTC application ID */
					appId: string;
					sessionId: string;
				};
				cookie?: never;
			};
			requestBody?: {
				content: {
					/**
					 * @example {
					 *       "sessionDescription": {
					 *         "sdp": "v=0\no=- 0 0 IN IP4 127.0.0.1\ns=-\nc=IN IP4 127.0.0.1\nt=0 0\nm=audio 4000 RTP/AVP 111\na=rtpmap:111 OPUS/48000/2\nm=video 4002 RTP/AVP 96\na=rtpmap:96 VP8/90000\n...\ntype: answer\n"
					 *       }
					 *     }
					 */
					"application/json": components["schemas"]["RenegotiateRequest"];
				};
			};
			responses: {
				/** @description OK */
				200: {
					headers: {
						vary?: string;
						[name: string]: unknown;
					};
					content: {
						/** @example {} */
						"application/json": components["schemas"]["RenegotiateResponse"];
					};
				};
			};
		};
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/apps/{appId}/sessions/{sessionId}/tracks/close": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		/** Close a local or remote track */
		put: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description WebRTC application ID */
					appId: string;
					sessionId: string;
				};
				cookie?: never;
			};
			requestBody?: {
				content: {
					"application/json": components["schemas"]["CloseTracksRequest"] &
						unknown;
				};
			};
			responses: {
				/** @description OK */
				200: {
					headers: {
						vary?: string;
						[name: string]: unknown;
					};
					content: {
						/**
						 * @example {
						 *       "sessionDescription": {
						 *         "sdp": "v=0\no=- 0 0 IN IP4 127.0.0.1\ns=-\nc=IN IP4 127.0.0.1\nt=0 0\nm=audio 4000 RTP/AVP 111\na=rtpmap:111 OPUS/48000/2\nm=video 4002 RTP/AVP 96\na=rtpmap:96 VP8/90000\n...\n",
						 *         "type": "answer"
						 *       },
						 *       "requiresImmediateRenegotiation": false,
						 *       "tracks": [
						 *         {
						 *           "mid": "7"
						 *         }
						 *       ]
						 *     }
						 */
						"application/json": components["schemas"]["CloseTracksResponse"];
					};
				};
			};
		};
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/apps/{appId}/sessions/{sessionId}/tracks/update": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		/** Change tracks by reusing existing transceivers */
		put: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description WebRTC application ID */
					appId: string;
					/** @description Current PeerConnection session ID */
					sessionId: string;
				};
				cookie?: never;
			};
			requestBody?: {
				content: {
					"application/json": components["schemas"]["UpdateTracksRequest"];
				};
			};
			responses: {
				/** @description OK */
				200: {
					headers: {
						vary?: string;
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["UpdateTracksResponse"];
					};
				};
			};
		};
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/apps/{appId}/sessions/{sessionId}/datachannels/establish": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Pull a server events channel to establish a data channel transport. It only allows to pull the server-events channel */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description WebRTC application ID */
					appId: string;
					/** @description Current PeerConnection session ID */
					sessionId: string;
				};
				cookie?: never;
			};
			requestBody?: {
				content: {
					"application/json": components["schemas"]["EstablishDataChannelsTransportRequest"];
				};
			};
			responses: {
				/** @description OK */
				200: {
					headers: {
						vary?: string;
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["EstablishDataChannelsTransportResponse"];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/apps/{appId}/sessions/{sessionId}/datachannels/new": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Solve the given data channel object(s) and add the data channel(s) to the WebRTC session. It requires to have a data channels transport established */
		post: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description WebRTC application ID */
					appId: string;
					/** @description Current PeerConnection session ID */
					sessionId: string;
				};
				cookie?: never;
			};
			requestBody?: {
				content: {
					"application/json": components["schemas"]["DataChannelsRequest"];
				};
			};
			responses: {
				/** @description OK */
				200: {
					headers: {
						vary?: string;
						[name: string]: unknown;
					};
					content: {
						"application/json": components["schemas"]["DataChannelsResponse"];
					};
				};
			};
		};
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/apps/{appId}/sessions/{sessionId}/datachannels/close": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		/** Close local or remote data channel(s) */
		put: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description WebRTC application ID */
					appId: string;
					sessionId: string;
				};
				cookie?: never;
			};
			requestBody?: {
				content: {
					"application/json": components["schemas"]["CloseDataChannelsRequest"] &
						unknown;
				};
			};
			responses: {
				/** @description OK */
				200: {
					headers: {
						vary?: string;
						[name: string]: unknown;
					};
					content: {
						/**
						 * @example {
						 *       "datachannels": [
						 *         {
						 *           "location": "remote",
						 *           "sessionId": "2a45361d5fd7cc14eface0587c276c94",
						 *           "dataChannelName": "1a037563-c35c-4bf6-a9ee-2b474cbb9a51",
						 *           "id": 2
						 *         }
						 *       ]
						 *     }
						 */
						"application/json": components["schemas"]["CloseDataChannelsResponse"];
					};
				};
			};
		};
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/apps/{appId}/sessions/{sessionId}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Return the list of tracks associated to the session */
		get: {
			parameters: {
				query?: never;
				header?: never;
				path: {
					/** @description WebRTC application ID */
					appId: string;
					sessionId: string;
				};
				cookie?: never;
			};
			requestBody?: never;
			responses: {
				/** @description OK */
				200: {
					headers: {
						vary?: string;
						[name: string]: unknown;
					};
					content: {
						/**
						 * @example {
						 *       "tracks": [
						 *         {
						 *           "location": "local",
						 *           "mid": "2",
						 *           "trackName": "1a037563-c35c-4bf6-a9ee-2b474cbb9a51",
						 *           "status": "active"
						 *         },
						 *         {
						 *           "location": "remote",
						 *           "mid": "7",
						 *           "sessionId": "2a45361d5fd7cc14eface0587c276c94",
						 *           "trackName": "2e037563-a35d-4bf6-a9ee-2d474cbb9a58",
						 *           "status": "active"
						 *         }
						 *       ]
						 *     }
						 */
						"application/json": components["schemas"]["GetSessionStateResponse"];
					};
				};
			};
		};
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		SessionDescription: {
			sdp?: string;
			/** @enum {string} */
			type?: "answer" | "offer";
		};
		TrackObject: {
			/**
			 * @description If you want to share a track, it should be local. If you want to play a track shared by a remote agent, it should be remote
			 * @enum {string}
			 */
			location?: "local" | "remote";
			/** @description mid associated to track's transceiver. It also can be prefixed with \# to reference an existing transceiver by its trackName */
			mid?: string;
			/** @description Session ID of the track owner. It should be set for remote tracks only */
			sessionId?: string;
			/** @description Given name for the track */
			trackName?: string;
			/** @description Make the associated transceiver bidirectional. This option works only when the SFU generates the offer */
			bidirectionalMediaStream?: boolean;
			/** @description Give a hint to the SFU about the transceiver kind. This is required when the SFU generates the offer */
			kind?: string;
			/** @description Simulcast configuration for the track */
			simulcast?: {
				/** @description Preferred RID for simulcast streams */
				preferredRid?: string;
				/**
				 * @description Controls what happens if there is not enough network resources available to send the preferredRid. 'none' means keep sending even if not enough bandwidth, 'asciibetical' uses a-z order to determine priority where a is most desirable and z is least desirable.
				 * @default none
				 * @enum {string}
				 */
				priorityOrdering: "none" | "asciibetical";
				/**
				 * @description Controls what happens when the rid currently being used or preferredRid is no longer being sent by the publisher. 'none' means do nothing, 'asciibetical' uses the next available layer after sorting the layers a-z.
				 * @default none
				 * @enum {string}
				 */
				ridNotAvailable: "none" | "asciibetical";
			};
		};
		CloseTrackObject: {
			/** @description mid associated to the track's transceiver to close */
			mid?: string;
		};
		TracksRequest: {
			sessionDescription?: components["schemas"]["SessionDescription"];
			tracks?: components["schemas"]["TrackObject"][];
			/** @description Assign a random track name to any new track in the offered SDP */
			autoDiscover?: boolean;
		};
		TracksResponse: {
			errorCode?: string;
			errorDescription?: string;
			requiresImmediateRenegotiation?: boolean;
			sessionDescription?: components["schemas"]["SessionDescription"];
			tracks?: (components["schemas"]["TrackObject"] & {
				errorCode?: string;
				errorDescription?: string;
			})[];
		};
		NewSessionRequest: {
			sessionDescription?: components["schemas"]["SessionDescription"];
		};
		NewSessionResponse: {
			errorCode?: string;
			errorDescription?: string;
			sessionDescription?: {
				sdp?: string;
				/** @enum {string} */
				type?: "answer" | "offer";
			};
			sessionId: string;
		};
		CloseTracksRequest: {
			sessionDescription?: components["schemas"]["SessionDescription"];
			tracks?: components["schemas"]["CloseTrackObject"][];
			/** @description True if you want to stop just the data flow for the tracks, no WebRTC renegotiation */
			force?: boolean;
		};
		CloseTracksResponse: {
			errorCode?: string;
			errorDescription?: string;
			sessionDescription?: components["schemas"]["SessionDescription"];
			tracks?: (components["schemas"]["CloseTrackObject"] & {
				errorCode?: string;
				errorDescription?: string;
			})[];
			requiresImmediateRenegotiation?: boolean;
		};
		GetSessionStateResponse: {
			errorCode?: string;
			errorDescription?: string;
			tracks?: (components["schemas"]["TrackObject"] & {
				/** @enum {string} */
				status?: "active" | "inactive" | "waiting";
			})[];
		};
		RenegotiateRequest: {
			sessionDescription?: components["schemas"]["SessionDescription"];
		};
		RenegotiateResponse: {
			errorCode?: string;
			errorDescription?: string;
			sessionDescription?: components["schemas"]["SessionDescription"];
		};
		ChangeTracksRequest: {
			/** @description Map of track IDs to track objects for changing tracks */
			tracks?: {
				[key: string]: components["schemas"]["TrackObject"];
			};
			sessionDescription?: components["schemas"]["SessionDescription"];
		};
		UpdateTracksRequest: {
			/** @description Array of track objects for updating tracks */
			tracks?: components["schemas"]["TrackObject"][];
			sessionDescription?: components["schemas"]["SessionDescription"];
		};
		UpdateTracksResponse: {
			errorCode?: string;
			errorDescription?: string;
			requiresImmediateRenegotiation?: boolean;
			/** @description Array of track objects with results */
			tracks?: (components["schemas"]["TrackObject"] & {
				errorCode?: string;
				errorDescription?: string;
			})[];
		};
		AdapterObject: {
			/**
			 * @description Use local to ingest media from an external endpoint. Use remote to stream media from an existing WebRTC track.
			 * @enum {string}
			 */
			location?: "local" | "remote";
			/** @description Session ID of the track owner. Required for remote adapters. */
			sessionId?: string;
			/** @description Track name to ingest into or stream from. */
			trackName?: string;
			/** @description WebSocket endpoint URL. */
			endpoint?: string;
			/**
			 * @description Codec for outgoing media on remote adapters. Use pcm for audio or jpeg for video.
			 * @enum {string}
			 */
			outputCodec?: "pcm" | "jpeg";
			/**
			 * @description Codec for incoming media on local adapters.
			 * @enum {string}
			 */
			inputCodec?: "pcm";
			/**
			 * @description Adapter mode. Use buffer for local adapters and stream for remote adapters.
			 * @enum {string}
			 */
			mode?: "stream" | "buffer";
			/** @description Unique identifier of the adapter instance. */
			adapterId?: string;
		};
		AdapterStatObject: {
			/** @description Unique identifier of the adapter instance. */
			adapterId?: string;
			/** @description Number of bytes processed before the adapter closed. */
			bytesProcessed?: number;
		};
		NewAdapterRequest: {
			tracks?: components["schemas"]["AdapterObject"][];
		};
		NewAdapterResponse: {
			errorCode?: string;
			errorDescription?: string;
			tracks?: (components["schemas"]["AdapterObject"] & {
				errorCode?: string;
				errorDescription?: string;
			})[];
		};
		CloseAdapterRequest: {
			tracks?: {
				/** @description Adapter identifier to close. */
				adapterId?: string;
			}[];
		};
		CloseAdapterResponse: {
			errorCode?: string;
			errorDescription?: string;
			tracks?: (components["schemas"]["AdapterStatObject"] & {
				errorCode?: string;
				errorDescription?: string;
			})[];
		};
		DataChannelObject: {
			/**
			 * @description Choose local to broadcast into the given dataChannelName. Choose remote to consume a broadcast from someone else
			 * @enum {string}
			 */
			location?: "local" | "remote";
			/** @description Session ID of the data channel owner. It should be set for remote data channels only */
			sessionId?: string;
			/** @description Given name for the data channel */
			dataChannelName?: string;
			/** @description Data channel id */
			id?: number;
		};
		DataChannelsRequest: {
			dataChannels?: components["schemas"]["DataChannelObject"][];
		};
		DataChannelsResponse: {
			errorCode?: string;
			errorDescription?: string;
			dataChannels?: (components["schemas"]["DataChannelObject"] & {
				errorCode?: string;
				errorDescription?: string;
			})[];
		};
		EstablishDataChannelsTransportRequest: {
			sessionDescription?: components["schemas"]["SessionDescription"];
			dataChannel?: components["schemas"]["DataChannelObject"];
		};
		EstablishDataChannelsTransportResponse: {
			errorCode?: string;
			errorDescription?: string;
			sessionDescription?: components["schemas"]["SessionDescription"];
			requiresImmediateRenegotiation?: boolean;
			dataChannel?: components["schemas"]["DataChannelObject"];
		};
		CloseDataChannelsRequest: {
			dataChannels?: components["schemas"]["DataChannelObject"][];
		};
		CloseDataChannelsResponse: {
			errorCode?: string;
			errorDescription?: string;
			dataChannels?: (components["schemas"]["DataChannelObject"] & {
				errorCode?: string;
				errorDescription?: string;
			})[];
		};
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
